import { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    code: "en",
    label: "English",
    flag: "🇺🇸",
    nav: {
      home: "Home",
      play: "Play",
      leaderboard: "Leaderboard",
      community: "Community",
      profile: "Profile",
      login: "Login",
      signup: "Sign Up",
      logout: "Logout",
    },
    home: {
      badge: "Competitive Brain Training",
      title1: "Train Your",
      title2: "Logic.",
      title3: "Dominate the Board.",
      subtitle: "A precision-built competitive platform for testing your reasoning under pressure. Climb the global leaderboard across three disciplines.",
      cta: "Start for Free",
      viewLeaderboard: "View Leaderboard",
      continuePlaying: "Continue Playing",
      builtFor: "Built for serious players",
      builtForSub: "Every mechanic is designed to maximize cognitive challenge and competitive depth.",
      ready: "Ready to compete?",
      readySub: "Create your account in seconds and start earning XP immediately.",
      createAccount: "Create Account",
      stats: { categories: "Categories", questions: "Questions", levels: "Levels", leaderboard: "Leaderboard" },
      features: [
        { title: "Adaptive Difficulty", desc: "Questions scale from easy to hard across Math Logic, Pattern Recognition, and Critical Thinking." },
        { title: "Timed Pressure", desc: "20 seconds per question. Score multipliers reward speed and accuracy in equal measure." },
        { title: "Global Rankings", desc: "Real-time leaderboard. Compete against players worldwide, track XP, levels, and best scores." },
        { title: "XP & Levels", desc: "Earn XP from every match. Level up through 10 tiers with animated progress tracking." },
      ],
    },
    auth: {
      welcomeBack: "Welcome back",
      signInSub: "Sign in to continue competing",
      email: "Email",
      password: "Password",
      signIn: "Sign In",
      signingIn: "Signing in...",
      orContinue: "or",
      continueGoogle: "Continue with Google",
      noAccount: "No account?",
      createOne: "Create one",
      joinArena: "Join the Arena",
      createSub: "Create your account and start competing",
      username: "Username",
      createAccount: "Create Account",
      creatingAccount: "Creating account...",
      alreadyHave: "Already have an account?",
      invalidCredentials: "Invalid email or password.",
      googleFailed: "Google login failed. Try again.",
      emailInUse: "Email already in use.",
      registrationFailed: "Registration failed. Try again.",
      usernameTooShort: "Username must be at least 3 characters.",
      passwordTooShort: "Password must be at least 6 characters.",
      minPassword: "Min. 6 characters",
    },
    play: {
      chooseCategory: "Choose a Category",
      chooseSub: "10 random questions per match. 20 seconds each. Score depends on speed and difficulty.",
      startMatch: "Start match",
      matchesPlayed: "Matches Played",
      bestScore: "Best Score",
      avgAccuracy: "Avg Accuracy",
      categories: [
        { label: "Math Logic", description: "Equations, arithmetic sequences, probability, and number theory." },
        { label: "Pattern Recognition", description: "Numerical sequences, letter patterns, and visual series." },
        { label: "Critical Thinking", description: "Logic puzzles, syllogisms, paradoxes, and reasoning." },
      ],
    },
    game: {
      score: "Score",
      accuracy: "Accuracy",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      matchComplete: "Match Complete",
      finalScore: "Final Score",
      correct: "Correct",
      xpEarned: "XP Earned",
      currentLevel: "Current Level",
      playAgain: "Play Again",
      categories: "Categories",
      timeLeft: "Time Left",
    },
    leaderboard: {
      title: "Leaderboard",
      subtitle: "Top 20 players ranked by best score. Updated in real-time.",
      live: "Live",
      you: "you",
      bestScore: "best score",
      noPlayers: "No players yet. Be the first!",
    },
    profile: {
      totalXP: "Total XP",
      bestScore: "Best Score",
      matches: "Matches",
      avgAccuracy: "Avg Accuracy",
      recentMatches: "Recent Matches",
      noMatches: "No matches yet. Play your first game!",
      score: "score",
    },
    community: {
      title: "Community",
      live: "Live",
      subtitle: "Share feedback and see what the community thinks of Logic Arena.",
      avgRating: "Avg Rating",
      reviews: "Reviews",
      stars: "Stars",
      signInPrompt: "Sign in to leave feedback",
      signIn: "Sign In",
      noFeedback: "No feedback yet. Be the first to share!",
      shareExperience: "Share your experience",
      writeFeedback: "Write your feedback...",
      post: "Post Feedback",
      posting: "Posting...",
      posted: "Feedback posted!",
      topComment: "Top Comment",
      delete: "Delete",
      sure: "Sure?",
      yes: "Yes",
      no: "No",
      waitSeconds: "Please wait {n} seconds before posting again.",
      tooShort: "Message must be at least 2 characters.",
      tooLong: "Message must be at most 500 characters.",
    },
    xp: { xpProgress: "XP Progress" },
  },

  id: {
    code: "id",
    label: "Indonesia",
    flag: "🇮🇩",
    nav: {
      home: "Beranda",
      play: "Bermain",
      leaderboard: "Papan Skor",
      community: "Komunitas",
      profile: "Profil",
      login: "Masuk",
      signup: "Daftar",
      logout: "Keluar",
    },
    home: {
      badge: "Pelatihan Otak Kompetitif",
      title1: "Latih",
      title2: "Logikamu.",
      title3: "Kuasai Papan Skor.",
      subtitle: "Platform kompetitif untuk menguji kemampuan berpikir kamu di bawah tekanan. Naiki papan skor global dalam tiga kategori.",
      cta: "Mulai Gratis",
      viewLeaderboard: "Lihat Papan Skor",
      continuePlaying: "Lanjut Bermain",
      builtFor: "Dibuat untuk pemain serius",
      builtForSub: "Setiap mekanik dirancang untuk memaksimalkan tantangan kognitif dan kedalaman kompetitif.",
      ready: "Siap bersaing?",
      readySub: "Buat akun dalam hitungan detik dan mulai kumpulkan XP sekarang.",
      createAccount: "Buat Akun",
      stats: { categories: "Kategori", questions: "Soal", levels: "Level", leaderboard: "Papan Skor" },
      features: [
        { title: "Kesulitan Adaptif", desc: "Soal berjenjang dari mudah hingga sulit di kategori Logika Matematika, Pengenalan Pola, dan Berpikir Kritis." },
        { title: "Tekanan Waktu", desc: "20 detik per soal. Multiplier skor menghargai kecepatan dan akurasi secara setara." },
        { title: "Peringkat Global", desc: "Papan skor real-time. Bersaing dengan pemain seluruh dunia, lacak XP, level, dan skor terbaik." },
        { title: "XP & Level", desc: "Dapatkan XP dari setiap pertandingan. Naiki 10 tingkat level dengan pelacakan progres animasi." },
      ],
    },
    auth: {
      welcomeBack: "Selamat datang kembali",
      signInSub: "Masuk untuk melanjutkan kompetisi",
      email: "Email",
      password: "Kata Sandi",
      signIn: "Masuk",
      signingIn: "Sedang masuk...",
      orContinue: "atau",
      continueGoogle: "Lanjutkan dengan Google",
      noAccount: "Belum punya akun?",
      createOne: "Buat sekarang",
      joinArena: "Bergabung ke Arena",
      createSub: "Buat akun dan mulai bersaing",
      username: "Nama Pengguna",
      createAccount: "Buat Akun",
      creatingAccount: "Membuat akun...",
      alreadyHave: "Sudah punya akun?",
      invalidCredentials: "Email atau kata sandi salah.",
      googleFailed: "Login Google gagal. Coba lagi.",
      emailInUse: "Email sudah digunakan.",
      registrationFailed: "Pendaftaran gagal. Coba lagi.",
      usernameTooShort: "Nama pengguna minimal 3 karakter.",
      passwordTooShort: "Kata sandi minimal 6 karakter.",
      minPassword: "Min. 6 karakter",
    },
    play: {
      chooseCategory: "Pilih Kategori",
      chooseSub: "10 soal acak per pertandingan. 20 detik setiap soal. Skor tergantung kecepatan dan kesulitan.",
      startMatch: "Mulai pertandingan",
      matchesPlayed: "Pertandingan",
      bestScore: "Skor Terbaik",
      avgAccuracy: "Rata-rata Akurasi",
      categories: [
        { label: "Logika Matematika", description: "Persamaan, deret aritmatika, probabilitas, dan teori bilangan." },
        { label: "Pengenalan Pola", description: "Deret angka, pola huruf, dan seri visual." },
        { label: "Berpikir Kritis", description: "Teka-teki logika, silogisme, paradoks, dan penalaran." },
      ],
    },
    game: {
      score: "Skor",
      accuracy: "Akurasi",
      easy: "Mudah",
      medium: "Sedang",
      hard: "Sulit",
      matchComplete: "Pertandingan Selesai",
      finalScore: "Skor Akhir",
      correct: "Benar",
      xpEarned: "XP Didapat",
      currentLevel: "Level Saat Ini",
      playAgain: "Main Lagi",
      categories: "Kategori",
      timeLeft: "Sisa Waktu",
    },
    leaderboard: {
      title: "Papan Skor",
      subtitle: "20 pemain teratas berdasarkan skor terbaik. Diperbarui secara real-time.",
      live: "Langsung",
      you: "kamu",
      bestScore: "skor terbaik",
      noPlayers: "Belum ada pemain. Jadilah yang pertama!",
    },
    profile: {
      totalXP: "Total XP",
      bestScore: "Skor Terbaik",
      matches: "Pertandingan",
      avgAccuracy: "Rata-rata Akurasi",
      recentMatches: "Pertandingan Terakhir",
      noMatches: "Belum ada pertandingan. Mainkan game pertamamu!",
      score: "skor",
    },
    community: {
      title: "Komunitas",
      live: "Langsung",
      subtitle: "Bagikan pendapat dan lihat apa yang komunitas pikirkan tentang Logic Arena.",
      avgRating: "Rating Rata-rata",
      reviews: "Ulasan",
      stars: "Bintang",
      signInPrompt: "Masuk untuk memberikan ulasan",
      signIn: "Masuk",
      noFeedback: "Belum ada ulasan. Jadilah yang pertama!",
      shareExperience: "Bagikan pengalamanmu",
      writeFeedback: "Tulis ulasanmu...",
      post: "Kirim Ulasan",
      posting: "Mengirim...",
      posted: "Ulasan terkirim!",
      topComment: "Komentar Terbaik",
      delete: "Hapus",
      sure: "Yakin?",
      yes: "Ya",
      no: "Tidak",
      waitSeconds: "Tunggu {n} detik sebelum posting lagi.",
      tooShort: "Pesan minimal 2 karakter.",
      tooLong: "Pesan maksimal 500 karakter.",
    },
    xp: { xpProgress: "Progres XP" },
  },

  es: {
    code: "es",
    label: "Español",
    flag: "🇪🇸",
    nav: {
      home: "Inicio",
      play: "Jugar",
      leaderboard: "Clasificación",
      community: "Comunidad",
      profile: "Perfil",
      login: "Iniciar sesión",
      signup: "Registrarse",
      logout: "Cerrar sesión",
    },
    home: {
      badge: "Entrenamiento Cerebral Competitivo",
      title1: "Entrena tu",
      title2: "Lógica.",
      title3: "Domina el Tablero.",
      subtitle: "Una plataforma competitiva para poner a prueba tu razonamiento bajo presión. Escala en el ranking global en tres disciplinas.",
      cta: "Comenzar Gratis",
      viewLeaderboard: "Ver Clasificación",
      continuePlaying: "Continuar Jugando",
      builtFor: "Hecho para jugadores serios",
      builtForSub: "Cada mecánica está diseñada para maximizar el desafío cognitivo y la profundidad competitiva.",
      ready: "¿Listo para competir?",
      readySub: "Crea tu cuenta en segundos y empieza a ganar XP de inmediato.",
      createAccount: "Crear Cuenta",
      stats: { categories: "Categorías", questions: "Preguntas", levels: "Niveles", leaderboard: "Clasificación" },
      features: [
        { title: "Dificultad Adaptativa", desc: "Las preguntas van de fácil a difícil en Lógica Matemática, Reconocimiento de Patrones y Pensamiento Crítico." },
        { title: "Presión de Tiempo", desc: "20 segundos por pregunta. Los multiplicadores de puntuación recompensan la velocidad y la precisión por igual." },
        { title: "Rankings Globales", desc: "Clasificación en tiempo real. Compite contra jugadores de todo el mundo, rastrea XP, niveles y mejores puntuaciones." },
        { title: "XP y Niveles", desc: "Gana XP en cada partida. Sube 10 niveles con seguimiento de progreso animado." },
      ],
    },
    auth: {
      welcomeBack: "Bienvenido de nuevo",
      signInSub: "Inicia sesión para seguir compitiendo",
      email: "Correo electrónico",
      password: "Contraseña",
      signIn: "Iniciar sesión",
      signingIn: "Iniciando sesión...",
      orContinue: "o",
      continueGoogle: "Continuar con Google",
      noAccount: "¿No tienes cuenta?",
      createOne: "Créala aquí",
      joinArena: "Únete a la Arena",
      createSub: "Crea tu cuenta y empieza a competir",
      username: "Nombre de usuario",
      createAccount: "Crear Cuenta",
      creatingAccount: "Creando cuenta...",
      alreadyHave: "¿Ya tienes cuenta?",
      invalidCredentials: "Correo o contraseña inválidos.",
      googleFailed: "Error al iniciar con Google. Inténtalo de nuevo.",
      emailInUse: "El correo ya está en uso.",
      registrationFailed: "Registro fallido. Inténtalo de nuevo.",
      usernameTooShort: "El nombre de usuario debe tener al menos 3 caracteres.",
      passwordTooShort: "La contraseña debe tener al menos 6 caracteres.",
      minPassword: "Mín. 6 caracteres",
    },
    play: {
      chooseCategory: "Elige una Categoría",
      chooseSub: "10 preguntas aleatorias por partida. 20 segundos cada una. La puntuación depende de la velocidad y dificultad.",
      startMatch: "Iniciar partida",
      matchesPlayed: "Partidas Jugadas",
      bestScore: "Mejor Puntuación",
      avgAccuracy: "Precisión Media",
      categories: [
        { label: "Lógica Matemática", description: "Ecuaciones, sucesiones aritméticas, probabilidad y teoría de números." },
        { label: "Reconocimiento de Patrones", description: "Sucesiones numéricas, patrones de letras y series visuales." },
        { label: "Pensamiento Crítico", description: "Acertijos lógicos, silogismos, paradojas y razonamiento." },
      ],
    },
    game: {
      score: "Puntuación",
      accuracy: "Precisión",
      easy: "Fácil",
      medium: "Medio",
      hard: "Difícil",
      matchComplete: "Partida Completada",
      finalScore: "Puntuación Final",
      correct: "Correctas",
      xpEarned: "XP Ganado",
      currentLevel: "Nivel Actual",
      playAgain: "Jugar de Nuevo",
      categories: "Categorías",
      timeLeft: "Tiempo Restante",
    },
    leaderboard: {
      title: "Clasificación",
      subtitle: "Los 20 mejores jugadores por puntuación. Actualizado en tiempo real.",
      live: "En vivo",
      you: "tú",
      bestScore: "mejor puntuación",
      noPlayers: "Aún no hay jugadores. ¡Sé el primero!",
    },
    profile: {
      totalXP: "XP Total",
      bestScore: "Mejor Puntuación",
      matches: "Partidas",
      avgAccuracy: "Precisión Media",
      recentMatches: "Partidas Recientes",
      noMatches: "Sin partidas aún. ¡Juega tu primera partida!",
      score: "puntuación",
    },
    community: {
      title: "Comunidad",
      live: "En vivo",
      subtitle: "Comparte tu opinión y ve lo que la comunidad piensa de Logic Arena.",
      avgRating: "Valoración Media",
      reviews: "Reseñas",
      stars: "Estrellas",
      signInPrompt: "Inicia sesión para dejar una reseña",
      signIn: "Iniciar sesión",
      noFeedback: "Sin reseñas aún. ¡Sé el primero!",
      shareExperience: "Comparte tu experiencia",
      writeFeedback: "Escribe tu reseña...",
      post: "Publicar Reseña",
      posting: "Publicando...",
      posted: "¡Reseña publicada!",
      topComment: "Mejor Comentario",
      delete: "Eliminar",
      sure: "¿Seguro?",
      yes: "Sí",
      no: "No",
      waitSeconds: "Espera {n} segundos antes de publicar de nuevo.",
      tooShort: "El mensaje debe tener al menos 2 caracteres.",
      tooLong: "El mensaje debe tener como máximo 500 caracteres.",
    },
    xp: { xpProgress: "Progreso XP" },
  },
};

const LangContext = createContext(null);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  const switchLang = (code) => {
    setLang(code);
    localStorage.setItem("lang", code);
  };

  const t = translations[lang] || translations.en;

  return (
    <LangContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
};
